language: node_js
node_js:
- '16'
cache:
  directories:
    - node_modules
install: npm ci
script: npm run build
before_deploy: npm run bundle -- --mode=production
deploy:
- provider: script
  skip_cleanup: true
  script: npm run deploy -- --verbose --stage dev
  on:
    branch: staging
- provider: script
  skip_cleanup: true
  script: npm run deploy -- --verbose --stage prod
  on:
    branch: master
