language: node_js
node_js:
- '14'
cache:
  directories:
    - node_modules
install: npm install
script: npm run build
before_deploy: npm run bundle
deploy:
- provider: script
  skip_cleanup: true
  script: npm run deploy -- --verbose --stage dev
  on:
    branch: staging
- provider: script
  skip_cleanup: true
  script: npm run deploy -- --verbose --stage prod
  on:
    branch: master
