service: regenesis-scraper

configValidationMode: error

package:
  patterns:
    - '!**'
    - dist.*

provider:
  name: aws
  runtime: nodejs16.x
  stage: ${opt:stage, 'dev'}
  memorySize: 128
  environment:
    AWS_ACCOUNT_ID: ${env:AWS_ACCOUNT_ID}
    GENESIS_URL: ${env:GENESIS_URL}
    GENESIS_UNAME: ${env:GENESIS_UNAME}
    GENESIS_PWORD: ${env:GENESIS_PWORD}
    SERVICE: ${self:service}
    STAGE: ${self:provider.stage}
    REGION: ${aws:region}
  iam:
    role:
      statements:
        -  Effect: "Allow"
           Action:
             - "dynamodb:Query"
             - "dynamodb:GetItem"
             - "dynamodb:PutItem"
           Resource: "arn:aws:dynamodb:${aws:region}:*:table/${self:service}-${self:provider.stage}"

resources:
  Resources:
    DynamoDBTableGrades:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-${self:provider.stage}
        AttributeDefinitions:
          - AttributeName: partition_key
            AttributeType: S
          - AttributeName: sort_key
            AttributeType: S
        KeySchema:
          - AttributeName: partition_key
            KeyType: HASH
          - AttributeName: sort_key
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

plugins:
  - serverless-offline
  - serverless-prune-plugin

custom:
  prune:
    automatic: true
    number: 2

functions:
  grades_read:
    handler: dist.grades_read
    events:
      - http:
          method: GET
          path: /read/{studentid}
          cors: true
      - http:
          method: GET
          path: /grades/{studentid}
          cors: true
      - http:
          method: GET
          path: /grades/{studentid}/{schoolyear}
          cors: true
      - http:
          method: GET
          path: /grades/{studentid}/{schoolyear}/{mp}
          cors: true
  grades_write:
    handler: dist.grades_write
    timeout: 16
    events:
      - schedule:
          name: update-2501419
          rate: rate(6 hours)
          input:
            studentid: 2501419
